### ISSUE TITLE
Not able to shutoff mediasync for local development

### ISSUE THREAD

**Issue by davemerwin** [sunlightlabs/django-mediasync#12]
My DEBUG=True

Here is my mediasync settings:

MEDIA_STATIC_ROOT = os.path.join(PROJECT_PATH, '..', 'site_media', 'static')
MEDIA_STATIC_URL = '/site_media/static/'
MEDIA_ROOT = os.path.join(PROJECT_PATH, os.pardir, '..', 'site_media', 'dynamic')
MEDIA_URL = '/site_media/dynamic/'
MEDIASYNC = {
    'MEDIA_ROOT': MEDIA_STATIC_ROOT,
    'MEDIA_URL': MEDIA_STATIC_URL,
    'BACKEND':'mediasync.backends.s3',
    'AWS_KEY':'XXXXXXXXXXXXXXXXXX',
    'AWS_SECRET':'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'AWS_BUCKET':'XXXXXXXXX',
    'DOCTYPE':'html5',
    'SERVE_REMOTE': True,
}
MEDIASYNC_CSS_PATH = 'css'
MEDIASYNC_JS_PATH = 'js'
MEDIASYNC_JOINED = {
    'all.css': ['reset.css','960.css','layout.css','typography.css','forms.css','rounded-corners.css'],
    'print.css': ['print.css'],
    'all.js': ['jquery-1.4.js','jquery-ui.js','site.js'],
}

Any ideas what I'm missing?

**Comment by davemerwin** [comment]
oops that initial VAR is getting cut off. It should read:

MEDIA_STATIC_ROOT = os.path.join(PROJECT_PATH, '..', 'site_media', 'static')
MEDIA_STATIC_URL = '/site_media/static/'

**Comment by davemerwin** [comment]
Ok, That didn't work either. Check out this gist. Sorry for the complication: http://gist.github.com/405264

**Comment by jcarbaugh** [comment]
Hey Dave, a few issues here. Your example is mixing the old and new style of settings. Sorry that the documentation hasn't made this clear, but the 2.0 version that is currently being worked on in the master branch has a different method of specifying the settings. Only settings within the MEDIASYNC dict are recognized.

I see that the documentation is wrong on the JOINED, CSS_PATH, and JS_PATH settings. It doesn't say that they need to be part of the MEDIASYNC dict, but they do. I've modified your gist to how I think the settings should look.

http://gist.github.com/405311

Finally, and I think this is the real problem here, is that SERVE_REMOTE is set to True. When True it will always try to serve media from the remote URL instead of the local instance. Unless you specifically want to serve remote media when DEBUG = False, you can leave the SERVE_REMOTE setting out. And when DEBUG = False, the media will _always_ be served remotely regardless of what SERVE_REMOTE is set to.

Let me know if that helps! I'll get the documentation fixed.

**Comment by davemerwin** [comment]
Oh, awesome. That was the fix. I had the syntaxes all mixed up. And the SERVE_REMOTE was set improperly as you said. Thanks for looking at the docs.

Thanks for the help!
