### ISSUE TITLE
running syncmedia gives: sync() takes at most 1 argument (2 given) 

### ISSUE THREAD

**Issue by davemerwin** [sunlightlabs/django-mediasync#13]
Here is the gist: http://gist.github.com/405974
And here are my settings: http://gist.github.com/405977

The error seems to be happening around the AWS bucket info? But the AWS info is right.

Any ideas? I can't see what is going wrong. I tried commenting out the variables to see if that was it and still no go. Doesn't work locally either.

**Comment by jcarbaugh** [comment]
Any chance you checked out your copy before May 7th? I pushed a fix that day for an issue with arguments to the sync method. Try doing a pull and see if the problem is fixed.

Sorry for the problems you've been having. The current master is definitely a work in progress. If you want something more stable, there is a version of mediasync available in PyPI: django-mediasync==1.0.1

**Comment by davemerwin** [comment]
Yeah, that was it. Thanks for the help. And no worries on the problems. This is kick ass software.

**Comment by davemerwin** [comment]
Ok, this is closed.
