### ISSUE TITLE
Better cache busting?

### ISSUE THREAD

**Issue by gtaylor** [sunlightlabs/django-mediasync#15]
If I read the documentation right, it is suggested that one alter the AWS_PREFIX_KEY to do cache busting. Wouldn't this result in another copy of all static media uploaded to S3? If this is the case, it seems highly undesirable for those with lots of static media.

Is there any other way to handle cache busting, other than re-uploading your entire static media store? If not, this seems like a pretty big issue, as it lengthens our deployment time substantially.

**Comment by gtaylor** [comment]
Perhaps an {% img "img/someimage.png" %} or {% media "img/someimage.png" %}  template tag that appends the time of last syncing via a GET parameter? This would require wrapping all static media URLs in said tag, but would be worth it for us if it meant not re-uploading everything.

**Comment by jcarbaugh** [comment]
I'm open to adding a cache busting feature. I haven't yet just because it wasn't important to the projects that had previously used mediasync.

I like the general idea that you propose. The database would be the best place to store the time of the last sync, but I definitely don't want to be hitting the database on each request just to get the sync timestamp. The app could read it once on startup and use the value, but then syncing new media would require restarting the app. What is a good trade-off here? Am I missing another option?

**Comment by gtaylor** [comment]
I'd honestly be happy with an optional value in settings.py that would append a GET attribute with the contents of the value in settings.py. This would leave it up to the user to decide what value they'd like to use for cache busting. In my case, I'd probably need to store it in another python module, rather than the DB (for my primary deployment).

**Comment by gtaylor** [comment]
Just to be clear, I'd just use one cache busting value for all media, instead of per-file. This is much simpler, and only requires the users to re-download media after a change. Not the end of the world, since new visitors to the site are also downloading all of the media on their first page load.

**Comment by jcarbaugh** [comment]
Add CACHE_BUSTER setting that is appended as a query string to media URLs. Closed by 54d48fa87d3f69646bc03ee95b0da98c5f602d7b.

**Comment by jcarbaugh** [comment]
Hey Greg, I just committed a change to add a CACHE_BUSTER setting in the MEDIASYNC configuration dictionary. CACHE_BUSTER can be a string, int, or a callable. If it's a callable, it will be passed the URL that is to be written in case you do want to configure per-URL query string parameters.

**Comment by gtaylor** [comment]
Looks good, but what is the solution for <img> and other tags? Might we add a generic template tag that just wraps a path and spits out a URL, rather than an entire tag for an arbitrary media type? IE: img, swf, etc? The alternative would be to manually append CACHE_BUSTER to all <img> tags with a context variable, which gets pretty repetetive.

**Comment by jcarbaugh** [comment]
Okay, I completely forgot about that. I just pushed a fix for the media_url template tag. It works exactly as it did before if no arguments are passed. Now you can pass a path into it to render the path with the cache buster.

```
<img src="{% media_url '/images/logo.png' %}">
```

renders as

```
<img src="http://assets.example.com/path/to/media/images/logo.png?1234">
```

**Comment by gtaylor** [comment]
Awesome, well done and appreciated!

**Comment by robhudson** [comment]
The default configuration of the popular caching proxy Squid used to make Squid not consider known URLs with changed query parameters as new URLs. Effectively, users behind a Squid proxy would not have their caches refreshed by the above cache busters.  It might be a good idea to include some sort of note in the documentation to left users decide if this "soft" cache busting will be fine, or if the "hard" cache busting of defining a new path, is the best choice.

I should probably refresh my knowledge on that at some point... I don't know if this has changed since I learned about it or not.
