### ISSUE TITLE
Asset Files (css/js) not being joined

### ISSUE THREAD

**Issue by davemerwin** [sunlightlabs/django-mediasync#2]
With the following settings: 

MEDIASYNC_JOINED = {
    'joined.css': ['reset.css','960.css','layout.css','rounded-corners.css','typography.css','forms.css','thedregs.css','print.css'],
    'joined.js': ['jquery-1.3.2.min.js','site.js'],
}

I'm not seeing the joined file being made or uploaded. However, the files are being synced to s3.

**Comment by davemerwin** [comment]
Sorry, to clarify, the single files are being made and loaded to s3. Not the joined files.

**Comment by jcarbaugh** [comment]
Hi Dave. I'm not able to reproduce the issue. Can you confirm that the joined files are not being pushed to S3? Also, are your css files in the media/styles directory and scripts in media/scripts? Are the joined files listed in the console when you run the syncmedia command? What revision of mediasync are you using? Thanks for the help!

**Comment by davemerwin** [comment]
sorry for the delayed response. I was on vacation.

Yes, They are NOT being pushed to S3. Yes the files are in the correct directories. I can see all of the files being moved to the proper places in S3, but the joined files are not being created and moved.

Any tips? Any suggestions for debugging?

Lemme know.

**Comment by jcarbaugh** [comment]
Hey Dave, I just got back from vacation as well. I'm at a loss for what could be causing the issue here. We are using mediasync on a number of projects and have not had this issue with any of them. We are using a fairly standardized project template so all of the projects are fairly similar.

Line 71 of mediasync/**init**.py is where the joined files are created. You may want to check that 1) the correct dirname is being used, 2) the correct media path is being created (line 86), and 3) the buffer is being filled (line 93).

Another place to check is in the push to S3. Line 143 is the client.put method that should return True if the push succeeds and False if it does not. You could add an else in there to show if the _sync_file method has been called, but the push to S3 failed.
