### ISSUE TITLE
Domain stripped off local media URL

### ISSUE THREAD

**Issue by meyer** [sunlightlabs/django-mediasync#36]
On my local machine I'm using MAMP to serve static media and I noticed that the default behaviour for URL generation is to parse the URL and use the path only. What's the logic behind this?

Here's the line: https://github.com/sunlightlabs/django-mediasync/blob/4124b220939b4bba40ad0f33e86fe548eed86086/mediasync/backends/__init__.py#L59

**Comment by jcarbaugh** [comment]
Hi Mike,

This was an attempt to get contrib.staticfiles to play nicely with mediasync. staticfiles automatically adds static serving of media to the urls configuration in dev mode and there is no way to turn it off. At one point I was able to get staticfiles to stop serving in development if the STATIC_URL settings included a domain and not just a path. So I'd set it to http://localhost:8000/static/, but still need the template tag to render only the path.

I've read much more about staticfiles since I committed this change and think that I'll have to overhaul how mediasync works to get it to play nicely with staticfiles.

I don't think I or anyone is using this hack now, so I can revert this commit and return STATIC_URL as is, if that would work for you.

**Comment by jezdez** [comment]
For the record, staticfiles doesn't actually add static serving to the URLs configuration automatically but wraps the default WSGI handler in its custom `runserver` management command with its own `StaticFilesHandler`. This can be disabled by using the `--no-static` option. I suggest to implement an own runserver command if you don't need that on the long run.

**Comment by wmdmark** [comment]
Any updates on this? This is very frustrating when trying to run a local media server.
