### ISSUE TITLE
pluggable processors/filters for minifying

### ISSUE THREAD

**Issue by jcarbaugh** [sunlightlabs/django-mediasync#6]
It would be useful to associate a processor/filter with a list of content types. Would file extensions work better than content types? Assuming the processor is a callable:

```
mediasync.processors.register(callable, [content types] OR [file extensions])
```

Defaults should still be provided. How would one go about unregistering the defaults? Or would you just specify CSS or JS instead of content types or file extensions? If this is the method that is used, then does the addition of a JS processor remove the default JS processor?

**Comment by gtaylor** [comment]
As crude as extensions are, mime type detection is spotty and unreliable at best unless your media assets are entirely under your control. This is typically not the case in our contract work. So I'd probably vote for extension-based processors at least initially (doesn't hurt to add content/mime type options, too).

As far as registering/unregistering, perhaps later register() calls override the old ones silently? This could be akin to assigning a variable one value, then re-assigning it later. I'd hate to have people worrying about getting double-registration exceptions thrown all over the place due to weird import and execution paths.

**Comment by jcarbaugh** [comment]
Done. Skipped registration/deregistration and went with a setting. You could probably programmatically add additional filters, but it's not going to be documented.
